apiVersion: skaffold/v1beta13
kind: Config
profiles:
	- name: staging
		helm:
			releases:
				- name: api-gateway
				chartPath: charts/api-gateway
				skipBuildDependencies: true
				values:
					image:
						repository: api-gateway
						tag: latest

build:
	googleCloudBuild:
		projectId: {$PROJECT_ID}
	artifacts:
		- image: api-gateway
			bazel:
				target: //apps/api/gateway:api_gateway_image.tar

googleCloudBuild:
	projectId: ${PROJECT_ID}
