apiVersion: v1
kind: Service
metadata:
	name: postgres
	namespace: accounts
spec:
	ports:
		- port: 5432
			targetPort: 5432
			protocol: TCP
	selector:
		stage: production
		name: postgres
		app: postgres
