apiVersion: extensions/v1beta1
kind: Deployment
metadata:
	name: postgres
	namespace: accounts
	labels:
		stage: production
		name: postgres
		app: postgres
spec:
	replicas: 1
	strategy:
		type: Recreate
	template:
		metadata:
			labels:
				stage: production
				name: postgres
				app: postgres
		spec:
			containers:
				- image: postgres:10.1
					name: postgres
					envFrom:
						- configMapRef:
								name: config
					ports:
						- containerPort: 5432
							name: postgres-5432
					volumeMounts:
						- name: postgres-disk
							mountPath: /var/lib/postgresql/data
			volumes:
				- name: postgres-disk
					gcePersistentDisk:
						fsType: ext4
						pdName: postgres-disk
